"""Create initial tables

Revision ID: 1271ed08ad8e
Revises: 
Create Date: 2025-02-24 20:10:47.940555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1271ed08ad8e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_url', sa.String(length=255), nullable=False),
    sa.Column('branch', sa.String(length=100), nullable=False),
    sa.Column('commit_hash', sa.String(length=40), nullable=True),
    sa.Column('scan_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('codeql_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.String(length=255), nullable=True),
    sa.Column('rule_index', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('start_line', sa.Integer(), nullable=True),
    sa.Column('start_column', sa.Integer(), nullable=True),
    sa.Column('end_column', sa.Integer(), nullable=True),
    sa.Column('fingerprint', sa.String(length=255), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dependency_check_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('dependency_name', sa.String(length=255), nullable=True),
    sa.Column('dependency_version', sa.String(length=100), nullable=True),
    sa.Column('vulnerability_id', sa.String(length=100), nullable=True),
    sa.Column('vulnerability_name', sa.String(length=255), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dependency_check_findings')
    op.drop_table('codeql_findings')
    op.drop_table('scans')
    # ### end Alembic commands ###
